/**
 * Figma Variables → tokens.css 동기화 스크립트
 * Usage: FIGMA_TOKEN=xxx node scripts/sync-tokens.mjs
 */

import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FILE_KEY = 'ovg86eZdOa16MRWkuQXY7s';
const TOKEN = process.env.FIGMA_TOKEN;
const OUT_PATH = join(__dirname, '../src/styles/tokens.css');

if (!TOKEN) {
  console.error('❌ FIGMA_TOKEN 환경변수가 필요합니다.');
  process.exit(1);
}

function rgbaToHex({ r, g, b, a }) {
  const toHex = (n) => Math.round(n * 255).toString(16).padStart(2, '0');
  if (a === undefined || a === 1) return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
  const ar = Math.round(a * 100) / 100;
  return `rgba(${Math.round(r * 255)}, ${Math.round(g * 255)}, ${Math.round(b * 255)}, ${ar})`;
}

function toKebab(name) {
  return name.replace(/\//g, '-').replace(/\s+/g, '-').toLowerCase();
}

async function fetchVariables() {
  const res = await fetch(
    `https://api.figma.com/v1/files/${FILE_KEY}/variables/local`,
    { headers: { 'X-Figma-Token': TOKEN } }
  );
  if (!res.ok) {
    const err = await res.json();
    throw new Error(`Figma API error: ${err.message}`);
  }
  return res.json();
}

async function main() {
  console.log('🔄 Figma Variables 동기화 시작...');

  const data = await fetchVariables();
  const { variableCollections, variables } = data.meta;

  const lines = [
    `/* ============================================================`,
    `   SKT Pattern Guide — Design Tokens`,
    `   Auto-generated by scripts/sync-tokens.mjs`,
    `   Last synced: ${new Date().toISOString().split('T')[0]}`,
    `   ============================================================ */`,
    '',
    ':root {',
  ];

  for (const variable of Object.values(variables)) {
    const collection = variableCollections[variable.variableCollectionId];
    if (!collection) continue;

    const defaultModeId = collection.defaultModeId;
    const value = variable.valuesByMode[defaultModeId];

    if (variable.resolvedType === 'COLOR' && value && typeof value === 'object' && 'r' in value) {
      const cssName = `--${toKebab(variable.name)}`;
      const cssValue = rgbaToHex(value);
      lines.push(`  ${cssName}: ${cssValue};`);
    } else if (variable.resolvedType === 'FLOAT' && typeof value === 'number') {
      const cssName = `--${toKebab(variable.name)}`;
      lines.push(`  ${cssName}: ${value}px;`);
    }
  }

  lines.push('}');

  const content = lines.join('\n') + '\n';
  writeFileSync(OUT_PATH, content, 'utf-8');

  const count = Object.keys(variables).length;
  console.log(`✅ ${count}개 토큰 동기화 완료 → ${OUT_PATH}`);
}

main().catch((err) => {
  console.error('❌ 동기화 실패:', err.message);
  process.exit(1);
});
